//  PrivateURLs.java
//
//  `bundle install`
//  `./appkeeper.sh yhdev`
//
//  Created by lijunjie on 16/06/02.
//  Copyright © 2016年 com.intfocus. All rights reserved.
//

// current app: [yhdev]
// automatic generated by app_keeper.rb
package com.intfocus.hx.general.util;

public class RSPrivateURLs {
    public final static String kAppCode = "ruishang";
    public final static String kThemeColor = "#53a93f";
    public final static String kBannerBgColor = "#53a93f";
    public final static String kBannerTextColor = "#ffffff";
    public final static String kInitPassword = "123456";

    public final static String kBaseUrl = "http://api-ruishang.idata.mobi";
    public final static String kBaseUrl1 = "http://10.0.3.2:4567";

    public final static String kPgyerAppId = "e22d108e745505bc9968884b0d4cbcfd";
    public final static String kPgyerUrl = "https://www.pgyer.com/ruishangplus-a";

    public final static String kUMAppId = "5705c952e0f55a391a0011cc";
    public final static String kWXAppId = "wx0ad40e5c84419ce2";
    public final static String kWXAppSecret = "fac49cd8a126145d7b0bd528306298d8";

    public final static boolean kDashboardAd = false;
    public final static boolean kDropMenuScan = true;
    public final static boolean kDropMenuSearch = true;
    public final static boolean kDropMenuVoice = true;
    public final static boolean kDropMenuUserInfo = true;

    public final static boolean kTabBar = true;
    public final static boolean kTabBarKPI = true;
    public final static boolean kTabBarAnalyse = true;
    public final static boolean kTabBarApp = true;
    public final static boolean kTabBarMessage = true;

    public final static boolean kSubjectComment = true;
    public final static boolean kSubjectShare = true;

}
